# ================================================
# ============== Plugins 
# ================================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

# ================================================
# ============== Key bindings
# ================================================

unbind r
bind r source-file ~/.tmux.conf

# bind-key h select-pane -L
# bind-key j select-pane -D
# bind-key k select-pane -U
# bind-key l select-pane -R

# Set vi yanking keybinds
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind -n M-H previous-window
bind -n M-L next-window

# ================================================
# ============== Options 
# ================================================

set -g prefix C-Space
set -g mouse on

# Windows and panes starting at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Open new panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Status bar
set-option -g status-position top
set -Fg 'status-format[0]' '#{status-format[0]}'
set -g 'status-format[1]' ''
set -g status 2

set -g default-terminal screen-256color
# enable 24bit color:
set-option -sa terminal-overrides ",xterm*:Tc"

# Override ESC-j and ESC-k moving line
set -sg escape-time 0 
set -g status-interval 0

# ================================================
# ============== START OF catppuccin config
# ================================================

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha

set -g status-left ""
set -g  status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_session}"

# ================================================
# END OF catppuccin config
# ================================================

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

